library("sqldf")
data <- read.csv.sql("household_power_consumption.txt",sql = "select * from file where Date in ('1/2/2007','2/2/2007')",sep=";",header=TRUE)
png('plot4.png')
par(mfrow = c(2,2))
x <- strptime(paste(data$Date,data$Time),format = "%d/%m/%Y %H:%M:%S")
plot(x,data$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(x,data$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(x,data$Sub_metering_1,type="n",ylab="Energy sub metering",xlab="")
lines(x,data$Sub_metering_1,type="l",col="black")
lines(x,data$Sub_metering_2,type="l",col="red")
lines(x,data$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = c(1,1,1),bty="n",cex=0.9)
plot(x,data$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
