library("sqldf")
data <- read.csv.sql("household_power_consumption.txt",sql = "select * from file where Date in ('1/2/2007','2/2/2007')",sep=";",header=TRUE)
png('plot2.png')
plot(strptime(paste(data$Date,data$Time),format = "%d/%m/%Y %H:%M:%S"),data$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()
